os: osx
osx_image: xcode9.1

language: crystal

env:
  - CXX=/usr/local/opt/llvm/bin/clang++

before_install:
  - brew update
  - brew install llvm mono
  - eval "$(gimme 1.9)"
install: make clean build

script: make test
